#!/usr/bin/env node
/**
 * Generates WebP variants for storefront images and writes generatedImageAssets.ts.
 * Source PNGs in src/assets/ are kept; optimized output goes to src/assets/optimized/.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const assetsRoot = join(__dirname, '../src/assets');
const optimizedDir = join(assetsRoot, 'optimized');
const generatedTs = join(__dirname, '../src/lib/generatedImageAssets.ts');

/** @type {Array<{ id: string; source: string; widths: number[]; quality?: number }>} */
const SHOES = [
  { id: 'blue-nike', source: 'Shoe_Design/blue nike.png', widths: [320, 640, 1200] },
  { id: 'gold-black-nike', source: 'Shoe_Design/gold black nike.png', widths: [320, 640, 1200] },
  { id: 'pink-nike', source: 'Shoe_Design/pink nike.png', widths: [320, 640, 1200] },
  { id: 'black-brown-nike', source: 'Shoe_Design/black and brown nike.png', widths: [320, 640, 1200] },
  { id: 'brown-pink-nike', source: 'Shoe_Design/brown pink nike.png', widths: [320, 640, 1200] },
];

/** @type {Array<{ id: string; source: string; widths: number[]; quality?: number }>} */
const BACKGROUNDS = [
  { id: 'blue-bg', source: 'Backgrounds/blue.png', widths: [1280, 1920], quality: 82 },
  { id: 'gold-bg', source: 'Backgrounds/gold.png', widths: [1280, 1920], quality: 82 },
  { id: 'pink-bg', source: 'Backgrounds/pink.png', widths: [1280, 1920], quality: 82 },
  { id: 'brown-bg', source: 'Backgrounds/brown.png', widths: [1280, 1920], quality: 82 },
  { id: 'brown-pink-bg', source: 'Backgrounds/brown pink.png', widths: [1280, 1920], quality: 82 },
];

/** @type {Array<{ id: string; source: string; widths: number[]; quality?: number }>} */
const LOGOS = [
  { id: 'logo-all-pages', source: 'Logo/LogoAllPages.png', widths: [270, 400] },
  { id: 'logo-all-pages-text', source: 'Logo/LogoAllPagesText.png', widths: [200, 400] },
  { id: 'logo-home-text', source: 'Logo/LogoHomePageText.png', widths: [200, 400] },
];

const ALL = [...SHOES, ...BACKGROUNDS, ...LOGOS];

await mkdir(optimizedDir, { recursive: true });

/** @type {Record<string, Record<number, string>>} */
const manifest = {};

for (const item of ALL) {
  const inputPath = join(assetsRoot, item.source);
  const input = await readFile(inputPath);
  manifest[item.id] = {};

  for (const width of item.widths) {
    const fileName = `${item.id}-${width}.webp`;
    const outputPath = join(optimizedDir, fileName);
    await sharp(input)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: item.quality ?? 85 })
      .toFile(outputPath);

    const relImport = `../assets/optimized/${fileName}`;
    manifest[item.id][width] = relImport;
    const stat = await readFile(outputPath);
    console.log(`  ${fileName} (${(stat.length / 1024).toFixed(1)} KB)`);
  }
}

function varName(id, width) {
  return `${id.replace(/-/g, '_')}_${width}`;
}

const importLines = [];
const shoeMapEntries = [];
const bgMapEntries = [];
const logoExports = [];

for (const item of ALL) {
  const widths = item.widths;
  const vars = widths.map((w) => {
    const name = varName(item.id, w);
    importLines.push(`import ${name} from '${manifest[item.id][w]}';`);
    return { w, name };
  });

  const defaultW = Math.max(...widths);
  const defaultVar = vars.find((v) => v.w === defaultW).name;
  const srcSetExpr = vars.map((v) => `\${${v.name}} ${v.w}w`).join(', ');

  const block = `{
    default: ${defaultVar},
    srcSet: \`${srcSetExpr}\`,
    widths: [${widths.join(', ')}],
  }`;

  if (SHOES.some((s) => s.id === item.id)) {
    shoeMapEntries.push(`  '${item.id}': ${block},`);
  } else if (BACKGROUNDS.some((b) => b.id === item.id)) {
    bgMapEntries.push(`  '${item.id}': ${block},`);
  } else {
    logoExports.push(`export const ${item.id.replace(/-/g, '_')} = ${block};`);
  }
}

const ts = `// AUTO-GENERATED by frontend/scripts/optimize-assets.mjs — do not edit by hand
${importLines.join('\n')}

export interface ResponsiveImageSet {
  default: string;
  srcSet: string;
  widths: number[];
}

export const shoeImageSets: Record<string, ResponsiveImageSet> = {
${shoeMapEntries.join('\n')}
};

export const backgroundImageSets: Record<string, ResponsiveImageSet> = {
${bgMapEntries.join('\n')}
};

${logoExports.join('\n\n')}

export function buildImgProps(
  set: ResponsiveImageSet,
  options: { sizes: string; alt: string; loading?: 'eager' | 'lazy'; fetchPriority?: 'high' | 'low' | 'auto' }
) {
  return {
    src: set.default,
    srcSet: set.srcSet,
    sizes: options.sizes,
    alt: options.alt,
    loading: options.loading ?? 'lazy',
    decoding: 'async' as const,
    ...(options.fetchPriority ? { fetchPriority: options.fetchPriority } : {}),
  };
}
`;

await writeFile(generatedTs, ts, 'utf8');
console.log(`\nWrote ${relative(join(__dirname, '..'), generatedTs)}`);
