// AUTO-GENERATED by frontend/scripts/optimize-assets.mjs — do not edit by hand
import blue_nike_320 from '../assets/optimized/blue-nike-320.webp';
import blue_nike_640 from '../assets/optimized/blue-nike-640.webp';
import blue_nike_1200 from '../assets/optimized/blue-nike-1200.webp';
import gold_black_nike_320 from '../assets/optimized/gold-black-nike-320.webp';
import gold_black_nike_640 from '../assets/optimized/gold-black-nike-640.webp';
import gold_black_nike_1200 from '../assets/optimized/gold-black-nike-1200.webp';
import pink_nike_320 from '../assets/optimized/pink-nike-320.webp';
import pink_nike_640 from '../assets/optimized/pink-nike-640.webp';
import pink_nike_1200 from '../assets/optimized/pink-nike-1200.webp';
import black_brown_nike_320 from '../assets/optimized/black-brown-nike-320.webp';
import black_brown_nike_640 from '../assets/optimized/black-brown-nike-640.webp';
import black_brown_nike_1200 from '../assets/optimized/black-brown-nike-1200.webp';
import brown_pink_nike_320 from '../assets/optimized/brown-pink-nike-320.webp';
import brown_pink_nike_640 from '../assets/optimized/brown-pink-nike-640.webp';
import brown_pink_nike_1200 from '../assets/optimized/brown-pink-nike-1200.webp';
import blue_bg_1280 from '../assets/optimized/blue-bg-1280.webp';
import blue_bg_1920 from '../assets/optimized/blue-bg-1920.webp';
import gold_bg_1280 from '../assets/optimized/gold-bg-1280.webp';
import gold_bg_1920 from '../assets/optimized/gold-bg-1920.webp';
import pink_bg_1280 from '../assets/optimized/pink-bg-1280.webp';
import pink_bg_1920 from '../assets/optimized/pink-bg-1920.webp';
import brown_bg_1280 from '../assets/optimized/brown-bg-1280.webp';
import brown_bg_1920 from '../assets/optimized/brown-bg-1920.webp';
import brown_pink_bg_1280 from '../assets/optimized/brown-pink-bg-1280.webp';
import brown_pink_bg_1920 from '../assets/optimized/brown-pink-bg-1920.webp';
import logo_all_pages_270 from '../assets/optimized/logo-all-pages-270.webp';
import logo_all_pages_400 from '../assets/optimized/logo-all-pages-400.webp';
import logo_all_pages_text_200 from '../assets/optimized/logo-all-pages-text-200.webp';
import logo_all_pages_text_400 from '../assets/optimized/logo-all-pages-text-400.webp';
import logo_home_text_200 from '../assets/optimized/logo-home-text-200.webp';
import logo_home_text_400 from '../assets/optimized/logo-home-text-400.webp';

export interface ResponsiveImageSet {
  default: string;
  srcSet: string;
  widths: number[];
}

export const shoeImageSets: Record<string, ResponsiveImageSet> = {
  'blue-nike': {
    default: blue_nike_1200,
    srcSet: `${blue_nike_320} 320w, ${blue_nike_640} 640w, ${blue_nike_1200} 1200w`,
    widths: [320, 640, 1200],
  },
  'gold-black-nike': {
    default: gold_black_nike_1200,
    srcSet: `${gold_black_nike_320} 320w, ${gold_black_nike_640} 640w, ${gold_black_nike_1200} 1200w`,
    widths: [320, 640, 1200],
  },
  'pink-nike': {
    default: pink_nike_1200,
    srcSet: `${pink_nike_320} 320w, ${pink_nike_640} 640w, ${pink_nike_1200} 1200w`,
    widths: [320, 640, 1200],
  },
  'black-brown-nike': {
    default: black_brown_nike_1200,
    srcSet: `${black_brown_nike_320} 320w, ${black_brown_nike_640} 640w, ${black_brown_nike_1200} 1200w`,
    widths: [320, 640, 1200],
  },
  'brown-pink-nike': {
    default: brown_pink_nike_1200,
    srcSet: `${brown_pink_nike_320} 320w, ${brown_pink_nike_640} 640w, ${brown_pink_nike_1200} 1200w`,
    widths: [320, 640, 1200],
  },
};

export const backgroundImageSets: Record<string, ResponsiveImageSet> = {
  'blue-bg': {
    default: blue_bg_1920,
    srcSet: `${blue_bg_1280} 1280w, ${blue_bg_1920} 1920w`,
    widths: [1280, 1920],
  },
  'gold-bg': {
    default: gold_bg_1920,
    srcSet: `${gold_bg_1280} 1280w, ${gold_bg_1920} 1920w`,
    widths: [1280, 1920],
  },
  'pink-bg': {
    default: pink_bg_1920,
    srcSet: `${pink_bg_1280} 1280w, ${pink_bg_1920} 1920w`,
    widths: [1280, 1920],
  },
  'brown-bg': {
    default: brown_bg_1920,
    srcSet: `${brown_bg_1280} 1280w, ${brown_bg_1920} 1920w`,
    widths: [1280, 1920],
  },
  'brown-pink-bg': {
    default: brown_pink_bg_1920,
    srcSet: `${brown_pink_bg_1280} 1280w, ${brown_pink_bg_1920} 1920w`,
    widths: [1280, 1920],
  },
};

export const logo_all_pages = {
    default: logo_all_pages_400,
    srcSet: `${logo_all_pages_270} 270w, ${logo_all_pages_400} 400w`,
    widths: [270, 400],
  };

export const logo_all_pages_text = {
    default: logo_all_pages_text_400,
    srcSet: `${logo_all_pages_text_200} 200w, ${logo_all_pages_text_400} 400w`,
    widths: [200, 400],
  };

export const logo_home_text = {
    default: logo_home_text_400,
    srcSet: `${logo_home_text_200} 200w, ${logo_home_text_400} 400w`,
    widths: [200, 400],
  };

export function buildImgProps(
  set: ResponsiveImageSet,
  options: { sizes: string; alt: string; loading?: 'eager' | 'lazy'; fetchPriority?: 'high' | 'low' | 'auto' }
) {
  return {
    src: set.default,
    srcSet: set.srcSet,
    sizes: options.sizes,
    alt: options.alt,
    loading: options.loading ?? 'lazy',
    decoding: 'async' as const,
    ...(options.fetchPriority ? { fetchPriority: options.fetchPriority } : {}),
  };
}
